version: '3'

services:
  redis:
    image: redis:5.0-rc4-alpine
    ports:
      - 6379:6379
    volumes:
      - dataVolume:/data
    command: ['redis-server', '--appendonly yes']

volumes:
  dataVolume: {}
