version: '3'

services:
  redis:
    image: redis:5.0-rc4-alpine
    volumes:
      - dataVolume:/data
    command: ['redis-server', '--appendonly yes']

  urlshortener:
    build: .
    environment:
      - REDIS=//redis:6379
    ports:
      - 127.0.0.1:3000:3000
    links:
      - redis

volumes:
  dataVolume: {}
